### ISSUE TITLE
No way to pass in query string parameters to API calls?

### ISSUE THREAD

**Issue by matthewgertner** [generalui/pivotaltracker#6]
I couldn't see a way to pass in parameters like `limit` and `offset`. I ended up patching the API call I am using like this:

```
Service.prototype.all = function(options, cb) { // cb(err, tasks[])
    if (typeof(options) === 'function' && typeof(cb) === 'undefined') {
        cb = options;
        options = null;
    }
    var err = this.configError();
    if (err) {
        cb(err, null);
    }
    else {
       ptutil.api.get(
            this.config.trackerToken,
            this.pathSegments(),
            options, // query
            this.config, // options
            function(error, res) {
                _callbackWithIterations(error, res, cb);
            });
    }
};
```

Am I missing something? If not, would you agree to an approach like this? I'll post a pull request in that case.

**Comment by robert-wallis** [comment]
Good question!  For endpoints that we know have query params there is an `options` param much like your example.  The only one I know of that we use is stories:
https://github.com/generalui/pivotaltracker/blob/master/lib/resources/story.js#L447

We use the `pivotaltracker` library in builder/chain like so:

```nodejs
var tracker = require('pivotaltracker');
var trackerClient = new tracker.Client({trackerToken:config.PIVOTAL_TOKEN, pivotalHost:config.PIVOTAL_HOST});
...
var opts = {
  offset: offset,
  limit: limit
};
trackerClient.project(projectID).stories.all(opts, function(error, stories) {
  cb(error, stories);
});
```

But by all means please issue pull requests if we are missing an endpoint that you need.

Thanks!
