### ISSUE TITLE
Add member to project

### ISSUE THREAD

**Issue by dahliacreative** [generalui/pivotaltracker#7]
Hi I'm having some trouble trying to add a member to a project.

Basically I check to see if someone is a member of a project, and if they aren't I try to add them via their email address.

This is the code I have, is it correct?
```
client.project(pivotal_id).memberships.create({email: process.env.pivotal_admin}, function(err, project) {
  console.log('Pivotal Admin added to project');
});
```

**Comment by dahliacreative** [comment]
For anyone else having the same issue as me, it's because 'role' is a required parameter, even though on the pivotal api docs it says it isn't. 

I also switched over to using the person ID instead of email, but it all seems to work now.

Here is my final code:

```
client.project(pivotal_id).memberships.create({person_id: process.env.pivotal_admin, role: 'member'}, function(err, membership) {
  // Cool stuff in here.
});
```

**Comment by robert-wallis** [comment]
Thanks for figuring it out, sorry I couldn't help I am on vacation and I
have a bad internet connection.
